version: '3.4'

services:
  web:
    build:
      context: .
      target: base
    command: bin/rails server -b 0.0.0.0
    volumes:
      - .:/rails
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
  # postgres:
  #   build:
  #     context: ./postgres
  #     dockerfile: Dockerfile.zhparser
  #   command: postgres -c shared_preload_libraries=zhparser
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  # postgres:
  #   build:
  #     context: ./postgres
  #     dockerfile: Dockerfile.jieba
  #   command: postgres -c shared_preload_libraries=pg_jieba
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  redis:
    image: redis:6
  meilisearch:
    image: getmeili/meilisearch:v1.0
    volumes:
      - meili-data:/meili_data

volumes:
  meili-data:
