version: '3.4'

services:
  web:
    build:
      context: .
      target: base
    command: bin/rails server -b 0.0.0.0
    volumes:
      - .:/rails
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
      - meilisearch
      # - elasticsearch
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
  # postgres:
  #   build:
  #     context: ./postgres
  #     dockerfile: Dockerfile.zhparser
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  # postgres:
  #   build:
  #     context: ./postgres
  #     dockerfile: Dockerfile.jieba
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  redis:
    image: redis:6
  meilisearch:
    image: getmeili/meilisearch:v1.0
    volumes:
      - meili-data:/meili_data
  # elasticsearch:
  #   image: elasticsearch:7.17.9
  #   environment:
  #     discovery.type: single-node

volumes:
  meili-data:
