FROM postgres:15

RUN apt-get update && apt-get install -y \
  build-essential \
  postgresql-server-dev-15 \
  wget \
  git

RUN wget -q -O - http://www.xunsearch.com/scws/down/scws-1.2.3.tar.bz2 | tar xjf - \
  && cd scws-1.2.3 \
  && ./configure \
  && make install \
  && cd .. \
  && rm -rf scws-1.2.3

RUN git clone https://github.com/amutu/zhparser.git \
  && cd zhparser \
  && make \
  && make install \
  && cd .. \
  && rm -rf zhparser
