FROM postgres:15 AS builder

RUN apt-get update \
  && apt-get install -y \
    build-essential \
    cmake \
    postgresql-server-dev-15 \
    git

RUN git clone --depth 1 --recurse-submodules --shallow-submodules https://github.com/jaiminpan/pg_jieba \
  && cd pg_jieba \
  && mkdir build \
  && cd build \
  && cmake -DPostgreSQL_TYPE_INCLUDE_DIR=/usr/include/postgresql/15/server .. \
  && make \
  && make install

FROM postgres:15

COPY --from=builder /usr/lib/postgresql/15/lib/pg_jieba.so /usr/lib/postgresql/15/lib/pg_jieba.so
COPY --from=builder /usr/share/postgresql/15/extension/pg_jieba* /usr/share/postgresql/15/extension/
COPY --from=builder /usr/share/postgresql/15/tsearch_data/jieba* /usr/share/postgresql/15/tsearch_data/

CMD ["postgres", "-c", "shared_preload_libraries=pg_jieba.so"]
