FROM postgres:15

RUN apt-get update && apt-get install -y \
  build-essential \
  cmake \
  postgresql-server-dev-15 \
  git

RUN git clone https://github.com/jaiminpan/pg_jieba \
  && cd pg_jieba \
  && git submodule update --init --recursive \
  && mkdir build \
  && cd build \
  && cmake -DPostgreSQL_TYPE_INCLUDE_DIR=/usr/include/postgresql/15/server .. \
  && make \
  && make install
